
ARG NODE_VERSION=22.19.0
FROM node:${NODE_VERSION}-alpine AS builder

WORKDIR /usr/src/app

# Copy package files and install all deps (including dev)
COPY package*.json ./
RUN npm install 

# Copy source and build
COPY . .
# RUN npm run build

CMD ["npm","run","dev"]


